const mexico = 
[{
    "first_name": "Eberhard",
    "salary": 61060
  }, {
    "first_name": "Elna",
    "salary": 31882
  }, {
    "first_name": "Onida",
    "salary": 3186
  }, {
    "first_name": "Laughton",
    "salary": 83617
  }, {
    "first_name": "Keen",
    "salary": 26676
  }, {
    "first_name": "Phelia",
    "salary": 74760
  }, {
    "first_name": "Emmalyn",
    "salary": 82281
  }, {
    "first_name": "Annemarie",
    "salary": 14723
  }, {
    "first_name": "Colan",
    "salary": 42691
  }, {
    "first_name": "Kattie",
    "salary": 66171
  }, {
    "first_name": "Dieter",
    "salary": 34409
  }, {
    "first_name": "Ransom",
    "salary": 49310
  }, {
    "first_name": "Joscelin",
    "salary": 86640
  }, {
    "first_name": "Grant",
    "salary": 94434
  }, {
    "first_name": "Millard",
    "salary": 19115
  }, {
    "first_name": "Johny",
    "salary": 36235
  }, {
    "first_name": "Audie",
    "salary": 52975
  }, {
    "first_name": "Charyl",
    "salary": 26327
  }, {
    "first_name": "Zach",
    "salary": 53588
  }, {
    "first_name": "Ely",
    "salary": 26762
  }, {
    "first_name": "Fredi",
    "salary": 23558
  }, {
    "first_name": "Constantine",
    "salary": 51335
  }, {
    "first_name": "Skipp",
    "salary": 91932
  }, {
    "first_name": "Con",
    "salary": 26851
  }, {
    "first_name": "Maxwell",
    "salary": 39758
  }, {
    "first_name": "Kikelia",
    "salary": 63412
  }, {
    "first_name": "Chlo",
    "salary": 84874
  }, {
    "first_name": "Rocky",
    "salary": 38517
  }, {
    "first_name": "Ertha",
    "salary": 27859
  }, {
    "first_name": "Miquela",
    "salary": 49861
  }, {
    "first_name": "Crosby",
    "salary": 31261
  }, {
    "first_name": "Dwain",
    "salary": 74891
  }, {
    "first_name": "Quintilla",
    "salary": 1554
  }, {
    "first_name": "Sayres",
    "salary": 90065
  }, {
    "first_name": "Ryon",
    "salary": 13286
  }, {
    "first_name": "Krispin",
    "salary": 84888
  }, {
    "first_name": "Gisella",
    "salary": 76280
  }, {
    "first_name": "Kit",
    "salary": 83904
  }, {
    "first_name": "Clarice",
    "salary": 70251
  }, {
    "first_name": "Vidovic",
    "salary": 6084
  }, {
    "first_name": "Wolfie",
    "salary": 24379
  }, {
    "first_name": "Judi",
    "salary": 80467
  }, {
    "first_name": "Hamish",
    "salary": 60771
  }, {
    "first_name": "Jillana",
    "salary": 91689
  }, {
    "first_name": "Freddie",
    "salary": 86071
  }, {
    "first_name": "Judah",
    "salary": 63489
  }, {
    "first_name": "Ellerey",
    "salary": 61035
  }, {
    "first_name": "Karyl",
    "salary": 53112
  }, {
    "first_name": "Wendell",
    "salary": 55324
  }, {
    "first_name": "Fayette",
    "salary": 62469
  }, {
    "first_name": "Shep",
    "salary": 31293
  }, {
    "first_name": "Miguela",
    "salary": 53106
  }, {
    "first_name": "Franky",
    "salary": 71464
  }, {
    "first_name": "Rozamond",
    "salary": 80847
  }, {
    "first_name": "Tamar",
    "salary": 65117
  }, {
    "first_name": "Cyndy",
    "salary": 9597
  }, {
    "first_name": "Auberon",
    "salary": 4920
  }, {
    "first_name": "Bert",
    "salary": 38515
  }, {
    "first_name": "Farrel",
    "salary": 49873
  }, {
    "first_name": "Herta",
    "salary": 21417
  }, {
    "first_name": "Kristi",
    "salary": 58711
  }, {
    "first_name": "Alysa",
    "salary": 19466
  }, {
    "first_name": "Arabel",
    "salary": 85663
  }, {
    "first_name": "Torey",
    "salary": 8596
  }, {
    "first_name": "Carmelita",
    "salary": 3551
  }, {
    "first_name": "Vina",
    "salary": 78672
  }, {
    "first_name": "Christoffer",
    "salary": 95505
  }, {
    "first_name": "Isis",
    "salary": 69879
  }, {
    "first_name": "Weston",
    "salary": 9402
  }, {
    "first_name": "Cinda",
    "salary": 54047
  }, {
    "first_name": "Loy",
    "salary": 21258
  }, {
    "first_name": "Morly",
    "salary": 33639
  }, {
    "first_name": "Zorine",
    "salary": 78415
  }, {
    "first_name": "Sibel",
    "salary": 84107
  }, {
    "first_name": "Sheila",
    "salary": 31364
  }, {
    "first_name": "Boyd",
    "salary": 59103
  }, {
    "first_name": "Adelheid",
    "salary": 92640
  }, {
    "first_name": "Darline",
    "salary": 94667
  }, {
    "first_name": "Salomi",
    "salary": 93177
  }, {
    "first_name": "Dav",
    "salary": 30974
  }, {
    "first_name": "Crawford",
    "salary": 85707
  }, {
    "first_name": "Shandy",
    "salary": 14005
  }, {
    "first_name": "Lazarus",
    "salary": 87925
  }, {
    "first_name": "Clarance",
    "salary": 66786
  }, {
    "first_name": "Rosalie",
    "salary": 16764
  }, {
    "first_name": "Drusie",
    "salary": 27082
  }, {
    "first_name": "Ros",
    "salary": 43590
  }, {
    "first_name": "Peirce",
    "salary": 66570
  }, {
    "first_name": "Kate",
    "salary": 50564
  }, {
    "first_name": "Almire",
    "salary": 32328
  }, {
    "first_name": "Jodi",
    "salary": 87452
  }, {
    "first_name": "Pauletta",
    "salary": 45442
  }, {
    "first_name": "Jobey",
    "salary": 53717
  }, {
    "first_name": "Bette",
    "salary": 15095
  }, {
    "first_name": "Mylo",
    "salary": 63484
  }, {
    "first_name": "Benedetta",
    "salary": 8313
  }, {
    "first_name": "Imelda",
    "salary": 46558
  }, {
    "first_name": "Clemmie",
    "salary": 87220
  }, {
    "first_name": "Cathe",
    "salary": 82607
  }, {
    "first_name": "Dukey",
    "salary": 76892
  }]
